"use client";
import { useEffect, useState } from "react";
import { BrowserMinecraftRuntime, detectCompatibility } from "@browser-client/browser-runtime";
import type { CompatibilityReport } from "@browser-client/shared";
const items: [keyof CompatibilityReport, string][] = [["wasm", "WebAssembly"], ["webgpu", "WebGPU"], ["webgl2", "WebGL 2"], ["opfs", "OPFS persistent storage"], ["workers", "Web Workers"], ["sharedArrayBuffer", "SharedArrayBuffer"], ["pointerLock", "Pointer Lock"]];
export default function Home() {
 const [report, setReport] = useState<CompatibilityReport>(); const [notice, setNotice] = useState("Check your browser before signing in.");
 useEffect(() => setReport(detectCompatibility()), []);
 const play = async () => { const runtime = new BrowserMinecraftRuntime(); await runtime.initialize(); setNotice(runtime.status.detail); };
 return <main><nav><span className="mark">▣</span><b>MINECRAFT <i>BROWSER CLIENT</i></b><span className="pill">RUNTIME LAB · NOT A GAME PORT</span></nav><section className="hero"><div><p className="eyebrow">LOCAL EXECUTION RESEARCH</p><h1>Your browser.<br/><em>Real client only.</em></h1><p className="lede">A production-shaped launcher shell that refuses to impersonate Minecraft. It is waiting for a lawful, browser-compatible actual-client adapter.</p><div className="actions"><button onClick={() => setNotice("Microsoft OAuth requires a registered server-side application. Configure auth-api before enabling sign-in.")}>Sign in with Microsoft <span>↗</span></button><button className="ghost" onClick={play}>Play <span>▶</span></button></div><p className="notice">{notice}</p></div><aside className="status"><header><span className="dot"/> SYSTEM READINESS</header><div className="runtime"><span>Execution target</span><strong>{report?.renderer === "unavailable" ? "No graphics API" : "Browser WASM adapter"}</strong><small>Actual Minecraft execution: 0% until an adapter runs verified Minecraft code.</small></div>{items.map(([k,label]) => <div className="check" key={k}><span>{label}</span><b className={report?.[k] ? "yes" : "no"}>{report ? (report[k] ? "SUPPORTED" : "UNAVAILABLE") : "CHECKING"}</b></div>)}<footer><span>RENDERER</span><b>{report?.renderer?.toUpperCase() ?? "CHECKING"}</b></footer></aside></section><section className="roadmap"><p className="eyebrow">ENGINEERING MILESTONES</p><div>{["Compatibility probe", "OAuth + secure session", "Entitlement verification", "Authorized asset acquisition", "Replaceable WASM runtime", "Actual-client execution"].map((x,i)=><article key={x} className={i === 0 ? "complete" : "pending"}><span>0{i+1}</span><b>{x}</b><small>{i === 0 ? "implemented" : i === 5 ? "blocked by adapter" : "planned"}</small></article>)}</div></section></main>;
}
