import { createHmac, randomBytes, createHash, timingSafeEqual } from "node:crypto";
export type Entitlement = "verified" | "unverified" | "unavailable";
export interface Session { sub: string; name?: string; microsoft: "authenticated"; entitlement: Entitlement; issuedAt: number; }
export interface OAuthConfig { clientId:string; clientSecret:string; tenantId:string; redirectUri:string; sessionSecret:string; }
export const requiredConfig = ["MICROSOFT_CLIENT_ID","MICROSOFT_CLIENT_SECRET","MICROSOFT_TENANT_ID","MICROSOFT_REDIRECT_URI","AUTH_SESSION_SECRET"] as const;
export function config(): OAuthConfig { const missing=requiredConfig.filter(k=>!process.env[k]); if(missing.length) throw new Error(`OAuth configuration is incomplete: ${missing.join(", ")}`); return {clientId:process.env.MICROSOFT_CLIENT_ID!,clientSecret:process.env.MICROSOFT_CLIENT_SECRET!,tenantId:process.env.MICROSOFT_TENANT_ID!,redirectUri:process.env.MICROSOFT_REDIRECT_URI!,sessionSecret:process.env.AUTH_SESSION_SECRET!}; }
const b64=(value:Buffer|string)=>Buffer.from(value).toString("base64url");
export const verifier=()=>b64(randomBytes(48)); export const state=()=>b64(randomBytes(32)); export const challenge=(v:string)=>b64(createHash("sha256").update(v).digest());
export function sign(payload:unknown, secret:string) { const data=b64(JSON.stringify(payload)); return `${data}.${createHmac("sha256",secret).update(data).digest("base64url")}`; }
export function verify<T>(token:string|undefined, secret:string):T|undefined { if(!token)return;const [data,signature]=token.split(".");if(!data||!signature)return;const expected=createHmac("sha256",secret).update(data).digest("base64url");if(signature.length!==expected.length||!timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return;try{return JSON.parse(Buffer.from(data,"base64url").toString()) as T;}catch{return;} }
export async function exchangeCode(code:string, c:OAuthConfig) { const response=await fetch(`https://login.microsoftonline.com/${encodeURIComponent(c.tenantId)}/oauth2/v2.0/token`,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,grant_type:"authorization_code",code,redirect_uri:c.redirectUri})});if(!response.ok)throw new Error("Microsoft authorization-code exchange failed.");return response.json() as Promise<{access_token:string}>; }
async function json(url:string, body:unknown, authorization?:string) { const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json",...(authorization?{authorization}: {})},body:JSON.stringify(body)});if(!r.ok)throw new Error("Minecraft identity service rejected the request.");return r.json() as Promise<any>; }
export async function verifyMinecraft(accessToken:string):Promise<Entitlement>{try{const xbl=await json("https://user.auth.xboxlive.com/user/authenticate",{Properties:{AuthMethod:"RPS",SiteName:"user.auth.xboxlive.com",RpsTicket:`d=${accessToken}`},RelyingParty:"http://auth.xboxlive.com",TokenType:"JWT"});const xsts=await json("https://xsts.auth.xboxlive.com/xsts/authorize",{Properties:{SandboxId:"RETAIL",UserTokens:[xbl.Token]},RelyingParty:"rp://api.minecraftservices.com/",TokenType:"JWT"});const uhs=xsts.DisplayClaims.xui[0].uhs;const mc=await json("https://api.minecraftservices.com/authentication/login_with_xbox",{identityToken:`XBL3.0 x=${uhs};${xsts.Token}`});const ent=await fetch("https://api.minecraftservices.com/entitlements/mcstore",{headers:{authorization:`Bearer ${mc.access_token}`}});if(!ent.ok)return "unavailable";const data=await ent.json() as {items?:unknown[]};return data.items?.length?"verified":"unverified";}catch{return "unavailable";}}
