import { unzipSync } from "fflate";
export interface DiscoveredMinecraftMethod { className: string; methodName: string; descriptor: string; code: Uint8Array; }
const safe = new Set([0x00, 0xb1]);
class Reader { constructor(readonly b: Uint8Array, public p=0) {} u1(){return this.b[this.p++]!;} u2(){const n=(this.u1()<<8)|this.u1();return n;} u4(){return (this.u2()*65536)+this.u2();} bytes(n:number){const r=this.b.slice(this.p,this.p+n);this.p+=n;return r;} }
function utf8(b: Uint8Array) { return new TextDecoder().decode(b); }
function parseClass(bytes: Uint8Array): DiscoveredMinecraftMethod[] {
 const r=new Reader(bytes); if(r.u4()!==0xcafebabe) return []; r.u2();r.u2();const cp:(string|number|undefined)[]=[]; const count=r.u2();
 for(let i=1;i<count;i++){const tag=r.u1(); if(tag===1){cp[i]=utf8(r.bytes(r.u2()));} else if(tag===3||tag===4){r.u4();} else if(tag===5||tag===6){r.u4();r.u4();i++;} else if(tag===7||tag===8||tag===16||tag===19||tag===20){cp[i]=r.u2();} else if(tag===9||tag===10||tag===11||tag===12||tag===18){r.u2();r.u2();} else if(tag===15){r.u1();r.u2();} else throw new Error(`Unsupported constant-pool tag ${tag}`); }
 r.u2(); const thisClass=r.u2();r.u2(); const interfaces=r.u2();r.bytes(interfaces*2); const skipMembers=()=>{for(let i=0,n=r.u2();i<n;i++){r.bytes(6);for(let j=0,a=r.u2();j<a;j++){r.u2();r.bytes(r.u4());}}}; skipMembers(); const found:DiscoveredMinecraftMethod[]=[]; const className=String(cp[Number(cp[thisClass])] ?? "").replaceAll("/", ".");
 for(let i=0,n=r.u2();i<n;i++){r.u2();const name=String(cp[r.u2()]??"");const descriptor=String(cp[r.u2()]??"");for(let j=0,a=r.u2();j<a;j++){const attr=String(cp[r.u2()]??"");const size=r.u4();if(attr!=="Code"){r.bytes(size);continue;} const start=r.p;r.u2();r.u2();const code=r.bytes(r.u4());const exceptions=r.u2();r.bytes(exceptions*8);const nested=r.u2();for(let x=0;x<nested;x++){r.u2();r.bytes(r.u4());}if(r.p!==start+size) throw new Error("Malformed Code attribute");if(code.length && [...code].every(op=>safe.has(op))) found.push({className,methodName:name,descriptor,code});}}
 return found;
}
export function discoverExecutableMinecraftMethod(jar: ArrayBuffer): DiscoveredMinecraftMethod | undefined { const entries=unzipSync(new Uint8Array(jar)); for(const [name, bytes] of Object.entries(entries)){if(name.startsWith("net/minecraft/")&&name.endsWith(".class")){const method=parseClass(bytes)[0];if(method)return method;}} }
export async function runOriginalBytecodeProbe(jar: ArrayBuffer, wasmUrl="/minecraft-bytecode-probe.wasm"): Promise<{method:DiscoveredMinecraftMethod; executedOpcodes:number}> { const method=discoverExecutableMinecraftMethod(jar); if(!method) throw new Error("No safe, executable Minecraft method found in this client artifact; bytecode interpreter needs more opcodes."); const response=await fetch(wasmUrl); if(!response.ok) throw new Error(`Bytecode probe WASM fetch failed (${response.status}).`); const {instance}=await WebAssembly.instantiateStreaming(response,{}); const e=instance.exports as unknown as {memory:WebAssembly.Memory;execute_jvm_code:(p:number,n:number)=>number;executed_opcode_count:()=>number}; const view=new Uint8Array(e.memory.buffer); const offset=1024;view.set(method.code,offset);if(e.execute_jvm_code(offset,method.code.length)!==1) throw new Error("WASM interpreter rejected the selected original Minecraft bytecode."); return {method,executedOpcodes:e.executed_opcode_count()}; }
