import type { CompatibilityReport, MinecraftExecution, RuntimeMetrics, RuntimeStatus } from "@browser-client/shared";
export interface GameRuntime { initialize(): Promise<void>; load(): Promise<void>; start(): Promise<void>; pause(): void; resume(): void; shutdown(): Promise<void>; }
export interface AdapterArtifact { wasmUrl: string; sha256: string; clientJarSha1: string; clientMainClass: string; }
export type MinecraftAdapterExports = WebAssembly.Exports & { minecraft_execution_probe?: WebAssembly.ExportValue; memory?: WebAssembly.ExportValue; };
export class RuntimeBlockedError extends Error { constructor(message: string) { super(message); this.name = "RuntimeBlockedError"; } }
export function detectCompatibility(): CompatibilityReport { const canvas = document.createElement("canvas"); const nav = navigator as Navigator & { gpu?: unknown; storage: StorageManager & { getDirectory?: () => Promise<FileSystemDirectoryHandle> } }; const webgl2 = Boolean(canvas.getContext("webgl2")); const webgpu = Boolean(nav.gpu); return { wasm: typeof WebAssembly !== "undefined", webgpu, webgl2, opfs: Boolean(nav.storage?.getDirectory), workers: typeof Worker !== "undefined", sharedArrayBuffer: typeof SharedArrayBuffer !== "undefined" && crossOriginIsolated, pointerLock: "requestPointerLock" in canvas, renderer: webgpu ? "webgpu" : webgl2 ? "webgl2" : "unavailable" }; }
/** Adapter contract: a probe returning 1 is allowed only after it invokes the declared client class; no JS mock path exists. */
export class BrowserMinecraftRuntime implements GameRuntime {
  status: RuntimeStatus = { phase: "idle", detail: "Waiting for a user-authorized Java-to-WASM adapter artifact." }; private artifact?: AdapterArtifact; private instance?: WebAssembly.Instance; private execution: MinecraftExecution = { verified: false }; private metrics: RuntimeMetrics = { jsWasmCalls: 0 };
  constructor(artifact?: AdapterArtifact) { this.artifact = artifact; }
  async initialize(): Promise<void> { this.status = this.artifact ? { phase: "initializing", detail: "Preparing the supplied Java-to-WASM adapter." } : { phase: "awaiting-artifacts", detail: "No authorized adapter artifact selected. Minecraft code is not executing." }; }
  async load(): Promise<void> { if (!this.artifact) throw new RuntimeBlockedError(this.status.detail); const started = performance.now(); const response = await fetch(this.artifact.wasmUrl, { integrity: `sha256-${this.artifact.sha256}`, credentials: "omit" }); if (!response.ok) throw new RuntimeBlockedError(`Adapter fetch failed (${response.status}).`); const module = await WebAssembly.compileStreaming(response); this.instance = await WebAssembly.instantiate(module, {}); this.metrics.loadedAt = Date.now(); this.metrics.startupMs = performance.now() - started; const memory = (this.instance.exports as MinecraftAdapterExports).memory; this.metrics.wasmMemoryBytes = memory instanceof WebAssembly.Memory ? memory.buffer.byteLength : undefined; this.status = { phase: "runtime-loaded", detail: "WASM adapter loaded; no Minecraft class execution has been attested." }; }
  async start(): Promise<void> { if (!this.instance || !this.artifact) throw new RuntimeBlockedError("Load an authorized adapter before start."); const probe = (this.instance.exports as MinecraftAdapterExports).minecraft_execution_probe; if (typeof probe !== "function") throw new RuntimeBlockedError("Adapter lacks the required actual-client execution probe."); this.metrics.jsWasmCalls++; if (probe() !== 1) throw new RuntimeBlockedError("Adapter did not attest to execution of the declared Minecraft class."); this.execution = { verified: true, className: this.artifact.clientMainClass, packageName: this.artifact.clientMainClass.split(".").slice(0, -1).join("."), invocation: "minecraft_execution_probe", evidence: `client JAR SHA-1 ${this.artifact.clientJarSha1}` }; this.status = { phase: "minecraft-executing", detail: `Verified adapter attestation for ${this.artifact.clientMainClass}.` }; }
  pause(): void { if (this.status.phase === "minecraft-executing") this.status = { phase: "minecraft-executing", detail: "Adapter pause requested." }; }
  resume(): void { if (this.status.phase === "minecraft-executing") this.status = { phase: "minecraft-executing", detail: "Adapter resume requested." }; }
  async shutdown(): Promise<void> { this.instance = undefined; this.execution = { verified: false }; this.status = { phase: "stopped", detail: "Runtime shut down." }; }
  getExecutionStatus(): RuntimeStatus { return this.status; } getLoadedModules(): string[] { return this.instance && this.artifact ? [this.artifact.wasmUrl] : []; } getRuntimeMetrics(): RuntimeMetrics { return { ...this.metrics }; } getMinecraftCodeExecution(): MinecraftExecution { return { ...this.execution }; }
}
export interface AssetManifestEntry { path: string; sha1: string; size: number; category?: "client-jar" | "asset-object" | "library" | "adapter"; }
export class GameAssetManager { async verifyAsset(file: ArrayBuffer, expectedSha1: string): Promise<boolean> { const digest = await crypto.subtle.digest("SHA-1", file); return [...new Uint8Array(digest)].map(v => v.toString(16).padStart(2, "0")).join("") === expectedSha1; } async cacheAsset(entry: AssetManifestEntry, data: ArrayBuffer): Promise<void> { const root = await navigator.storage.getDirectory(); const file = await root.getFileHandle(`asset-${entry.sha1}`, { create: true }); const stream = await file.createWritable(); await stream.write(data); await stream.close(); } async invalidateCache(): Promise<void> { const root = await navigator.storage.getDirectory(); const iterable = root as FileSystemDirectoryHandle & { entries(): AsyncIterable<[string, FileSystemHandle]> }; for await (const [name] of iterable.entries()) if (name.startsWith("asset-")) await root.removeEntry(name); } }
export { discoverExecutableMinecraftMethod, runOriginalBytecodeProbe } from "./class-probe";
